name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install Dependencies
        run: pnpm install

      - name: Check asset optimisation
        run: pnpm run check:assets

      - name: Run Lint
        run: pnpm run lint

      - name: Run Build
        run: pnpm run build
